version: 0.2

phases:
  build:
    commands:
      - echo "Deploying website to S3..."
      - aws s3 sync . s3://your-static-site-bucket2026 --delete --exclude ".git/*" --exclude "buildspec.yaml"

artifacts:
  files:
    - '**/*'
